# imports and constants

In [35]:
import pandas as pd

from os.path import join as join_pth
import matplotlib.pyplot as plt
import random
from IPython.core.display_functions import display
import seaborn as sns
# % matplotlib inline
sns.set_style('whitegrid')
import torch
from src import *
from src import data_loader,models,model_training
from torch.utils.data.dataloader import  DataLoader
from sklearn.model_selection import train_test_split

In [36]:
from importlib import reload,import_module

reload(data_loader)
reload(data_preprocessing)
reload(models)
reload(model_training)

<module 'src.model_training' from 'D:\\2022 acheivments\\Projects\\DeepLearning NanoDegree\\Rossmann-Store-Sales\\src\\model_training.py'>

In [37]:
raw_dataset_path = "../dataset/raw"
prep_dataset_path="../dataset/prep"
nn_model_weights_pth="../model_weights/nn_model"
nn_model_train_data_pth="../train_data/nn_model"

# roadmap
- data preparation after analysis run bulk preprocessing functions that have all preprocessing and feature engineering done at the analysis section
- start with the neural network without lstm layers and get the best score after hyperparameters tuning
    - create data loader for the neural network
    - find the best hyperparameters for the first epochs
    - train the model on the best hyperparameters

# Data preparation
- after analysing , handling outliers the data and do feature engineering on the data columns in the [rossmann-store-sales-analysis](./Rossmann-Store-Sales.ipynb) notebook column by column
- all steps are combined in the [data_preprocessing.py](../src/data_preprocessing.py) module for bulk preprocessing
    - store data preprocessing and feature engineering
    - store_sales preprocessing and feature engineering
    - merging store data and store sales and add new columns



In [38]:
stores_df = pd.read_csv(join_pth(raw_dataset_path, "store.csv"), low_memory=False)
stores_sales_df = pd.read_csv(join_pth(raw_dataset_path, "train.csv"), low_memory=False)

# Sales bulk preprocessing
stores_sales_df_prep=data_preprocessing.store_sales_prep(stores_sales_df=stores_sales_df)

# Store data bulk preprocessing
stores_data_df_prep=data_preprocessing.store_data_prep(store_data_df=stores_df)

# merge and do bulk preprocessing
merge_prep=data_preprocessing.merge_store_sales(sales_data_df=stores_sales_df_prep,store_data_df=stores_data_df_prep)

# drop closed stores data and open column
merge_prep=data_preprocessing.drop_closed_days(merge_prep)



In [39]:
merge_prep.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 844392 entries, 0 to 1017207
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype   
---  ------                --------------   -----   
 0   Store                 844392 non-null  int64   
 1   DayOfWeek             844392 non-null  category
 2   Sales                 844392 non-null  int64   
 3   Promo                 844392 non-null  category
 4   StateHoliday          910 non-null     object  
 5   SchoolHoliday         844392 non-null  category
 6   month                 844392 non-null  int64   
 7   day                   844392 non-null  int64   
 8   StoreType             844392 non-null  category
 9   Assortment            844392 non-null  category
 10  CompetitionDistance   844392 non-null  float64 
 11  Promo2                844392 non-null  category
 12  Promo2Since           844392 non-null  float64 
 13  CompetitionOpenSince  844392 non-null  float64 
 14  isPromoMonth          844392 non-nu

In [40]:
# hot-encode the categorical data
encoded_data=data_preprocessing.hot_encoding(merged_data=merge_prep)

In [41]:
encoded_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 844392 entries, 0 to 1017207
Data columns (total 28 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   Store                   844392 non-null  float64
 1   Sales                   844392 non-null  float64
 2   Promo                   844392 non-null  float64
 3   SchoolHoliday           844392 non-null  float64
 4   month                   844392 non-null  float64
 5   day                     844392 non-null  float64
 6   CompetitionDistance     844392 non-null  float64
 7   Promo2                  844392 non-null  float64
 8   Promo2Since             844392 non-null  float64
 9   CompetitionOpenSince    844392 non-null  float64
 10  isPromoMonth            844392 non-null  float64
 11  DayOfWeek_1             844392 non-null  float64
 12  DayOfWeek_2             844392 non-null  float64
 13  DayOfWeek_3             844392 non-null  float64
 14  DayOfWeek_4        

In [42]:
train_data,test_data=train_test_split(encoded_data,test_size=0.2)



In [43]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 675513 entries, 92895 to 1003811
Data columns (total 28 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   Store                   675513 non-null  float64
 1   Sales                   675513 non-null  float64
 2   Promo                   675513 non-null  float64
 3   SchoolHoliday           675513 non-null  float64
 4   month                   675513 non-null  float64
 5   day                     675513 non-null  float64
 6   CompetitionDistance     675513 non-null  float64
 7   Promo2                  675513 non-null  float64
 8   Promo2Since             675513 non-null  float64
 9   CompetitionOpenSince    675513 non-null  float64
 10  isPromoMonth            675513 non-null  float64
 11  DayOfWeek_1             675513 non-null  float64
 12  DayOfWeek_2             675513 non-null  float64
 13  DayOfWeek_3             675513 non-null  float64
 14  DayOfWeek_4    

<p style="font-size:18;font-weight:bold">Save preprocessed data</p>

In [44]:
file_name="merged_sales_train.csv"
train_data.to_csv(join_pth(prep_dataset_path,file_name),index=False)

file_name="merged_sales_test.csv"
test_data.to_csv(join_pth(prep_dataset_path,file_name),index=False)

# Data Loader
- load preprocessed data csv
- create neural network model data loader

In [45]:
file_name="merged_sales_train.csv"
sales_train_dataset=pd.read_csv(join_pth(prep_dataset_path,file_name))

file_name="merged_sales_test.csv"
sales_test_dataset=pd.read_csv(join_pth(prep_dataset_path,file_name))
sales_train_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 675513 entries, 0 to 675512
Data columns (total 28 columns):
 #   Column                  Non-Null Count   Dtype  
---  ------                  --------------   -----  
 0   Store                   675513 non-null  float64
 1   Sales                   675513 non-null  float64
 2   Promo                   675513 non-null  float64
 3   SchoolHoliday           675513 non-null  float64
 4   month                   675513 non-null  float64
 5   day                     675513 non-null  float64
 6   CompetitionDistance     675513 non-null  float64
 7   Promo2                  675513 non-null  float64
 8   Promo2Since             675513 non-null  float64
 9   CompetitionOpenSince    675513 non-null  float64
 10  isPromoMonth            675513 non-null  float64
 11  DayOfWeek_1             675513 non-null  float64
 12  DayOfWeek_2             675513 non-null  float64
 13  DayOfWeek_3             675513 non-null  float64
 14  DayOfWeek_4         

In [46]:
nn_sales_train_dataset=data_loader.NNSalesDataset(sales_train_dataset)
nn_sales_test_dataset=data_loader.NNSalesDataset(sales_test_dataset)

In [47]:
# dataset testing
dataset_iter=iter(nn_sales_train_dataset)
x,y=next(dataset_iter)
print(x)
print(x.shape)
print(y)

tensor([0.0000, 1.0000, 9.0000, 2.0000, 0.1500, 1.0000, 0.0000, 0.0000, 0.0000,
        1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000])
torch.Size([26])
tensor([7177.])


In [48]:
display(merge_prep.iloc[0])
display(encoded_data.iloc[0])
display(x)
display(y)


Store                       1
DayOfWeek                   5
Sales                    5263
Promo                       1
StateHoliday              NaN
SchoolHoliday               1
month                       7
day                        31
StoreType                   c
Assortment                  a
CompetitionDistance      1.27
Promo2                      0
Promo2Since               0.0
CompetitionOpenSince      0.0
isPromoMonth            False
Name: 0, dtype: object

Store                        1.00
Sales                     5263.00
Promo                        1.00
SchoolHoliday                1.00
month                        7.00
day                         31.00
CompetitionDistance          1.27
Promo2                       0.00
Promo2Since                  0.00
CompetitionOpenSince         0.00
isPromoMonth                 0.00
DayOfWeek_1                  0.00
DayOfWeek_2                  0.00
DayOfWeek_3                  0.00
DayOfWeek_4                  0.00
DayOfWeek_5                  1.00
DayOfWeek_6                  0.00
DayOfWeek_7                  0.00
StateHoliday_christmas       0.00
StateHoliday_easter          0.00
StateHoliday_public          0.00
StoreType_a                  0.00
StoreType_b                  0.00
StoreType_c                  1.00
StoreType_d                  0.00
Assortment_a                 1.00
Assortment_b                 0.00
Assortment_c                 0.00
Name: 0, dtype: float64

tensor([0.0000, 1.0000, 9.0000, 2.0000, 0.1500, 1.0000, 0.0000, 0.0000, 0.0000,
        1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000])

tensor([7177.])

In [49]:
batch_size=64
nn_sales_train_dataloader=DataLoader(nn_sales_train_dataset,batch_size=batch_size,shuffle=True)
nn_sales_test_dataloader=DataLoader(nn_sales_test_dataset,batch_size=batch_size,shuffle=True)

In [50]:
# Data loader testing
dataloader_iter=iter(nn_sales_train_dataloader)
x,y=next(dataloader_iter)
print(x.shape)
print(y.shape)

torch.Size([64, 26])
torch.Size([64, 1])


In [ ]:
input_size=nn_sales_train_dataloader.dataset.no_cols
hidden_shape=[256,32]
output_size=1
dropout_prop=0.5
nn_model=models.SalesNN(input_size,hidden_shape,output_size,dropout_prop)
train_losses,valid_losses=model_training.nn_model_train(nn_model,nn_sales_train_dataloader,nn_sales_test_dataloader,10,last_weights=True,train_data_dir=nn_model_train_data_pth,weights_dir=nn_model_weights_pth)

 training epoch 1 time Taken (m) = 1.83 Avg Train_Loss=11146826.16210327438731
 Test  time Taken (m) = 2.23 Avg Test_Loss=7466564.36926866s=7466293.60557242355
 epoch 1 train_loss =11146826.16210327 test_loss=7466564.36926866 total_time= 4.0600000000000005
 training epoch 2 time Taken (m) = 2.53 Avg Train_Loss=10692289.75066319574385783
 Test  time Taken (m) = 2.5 Avg Test_Loss=7155556.12154225ss=7156471.854150876827
 epoch 2 train_loss =10692289.75066319 test_loss=7155556.12154225 total_time= 5.029999999999999
new minimum test loss 7155556.12154225  achieved, model weights saved 
 training epoch 3 time Taken (m) = 2.17 Avg Train_Loss=10521124.2018711513265247
 Test  time Taken (m) = 2.16 Avg Test_Loss=7271011.54367185s=7269205.61286963412
 epoch 3 train_loss =10521124.20187115 test_loss=7271011.54367185 total_time= 4.33
 training epoch 4 time Taken (m) = 2.19 Avg Train_Loss=10420944.6676219882206973
 Test  time Taken (m) = 2.08 Avg Test_Loss=6987923.60685866s=6986471.362964378867
 epo